name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.13']
        os: [ubuntu-latest]
    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      env:
        WSK_INSTALL: https://github.com/apache/openwhisk-cli/releases/download/1.0.0/OpenWhisk_CLI-1.0.0-linux-amd64.tgz
        NVM_INSTALL: https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh 
      run: |
        curl -sL $WSK_INSTALL | sudo tar xzvf - -C /usr/bin wsk
        curl -o- "$NVM_INSTALL" | bash
        source $HOME/.nvm/nvm.sh
        nvm install v10
        sudo apt-get -y install httpie
        git clone https://github.com/sstephenson/bats.git
        cd bats
        sudo ./install.sh /usr/local


    - name: Build
      shell: bash
      env: 
        DOCKER_HUB_ACCESS_TOKEN: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      run: |
        source $HOME/.nvm/nvm.sh
        nvm use v10
        docker login -u iosdk -p "$DOCKER_HUB_ACCESS_TOKEN"
        make

    # uncomment this if you need to debug
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
